[project]
name = "qol-pack"
description = "Collapsible Nested Menus and Save Workflow as PNG"
version = "0.2.0"
license = {file = "LICENSE"} 

[project.urls]
Repository = "https://github.com/BobRandomNumber/ComfyUI-QoL-Pack"

[tool.comfy]
PublisherId = "bobrandomnumber"
DisplayName = "QoL-Pack"

